// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CopyInclude
{
    internal sealed partial class Vsix
    {
        public const string Id = "CopyInclude.fb140b0b-ea68-4333-8ec3-7ed24ef4a289";
        public const string Name = "Copy Include";
        public const string Description = @"Adds a custom formated path copying command when right clicking opened documents.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Julien Charbonneau";
        public const string Tags = "";
    }
}
