// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CopyInclude
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string CopyIncludeString = "189edcf7-ed70-4dce-97e9-d31ee6dba57d";
        public static Guid CopyInclude = new Guid(CopyIncludeString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int DocumentsGroup = 0x0001;
        public const int SolutionExplorerGroup = 0x0002;
        public const int CopyIncludeLocalCommand = 0x0100;
        public const int CopyIncludeExternCommand = 0x0200;
    }
}